return {
	{ "ellisonleao/gruvbox.nvim" },
	{ "catppuccin/nvim" },
	{ "folke/tokyonight.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "marko-cerovac/material.nvim" },
	{ "shaunsingh/seoul256.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "rose-pine/neovim" },
	{ "sainnhe/sonokai" },
	{ "sainnhe/edge" },
	{ "sainnhe/gruvbox-material" },
	{ "sainnhe/everforest", priority = 1000 },
	{ "askfiy/visual_studio_code" },
	{ "uloco/bluloco.nvim", dependencies = { "rktjmp/lush.nvim" } },
}
