return {
	{ "ellisonleao/gruvbox.nvim" },
	{ "catppuccin/nvim", priority=1000 },
	{ "folke/tokyonight.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "marko-cerovac/material.nvim" },
	{ "shaunsingh/seoul256.nvim" },
	{ "shaunsingh/nord.nvim" },
	{ "rose-pine/neovim" },
	{ "sainnhe/sonokai" },
	{ "sainnhe/edge" },
	{ "sainnhe/gruvbox-material" },
	{ "sainnhe/everforest" },
	{ "askfiy/visual_studio_code" },
}
